//Colors
#define CLR_SERVER 								0xFFFF00AA
#define CLR_ALERT								0xFF0F0F00
#define CLR_INFORMATION							0x7fff00ff
#define CLR_CMD 0xFFD700FF

#define CLR_WHITE 								0xFFFFFFFF
#define CLR_BLACK								0x00000000
#define CLR_GREY 								0xAFAFAFAA

#define CLR_RED									0xAA3333AA
#define CLR_DARKRED 							0x660000AA
#define CLR_ORANGE 								0xFF9900AA
#define CLR_YELLOW								0xFFFF00AA
#define CLR_GREEN 								0x33AA33AA
#define CLR_LIGHTGREEN							0x7fff00ff
#define CLR_LIGHTBLUE							0x33CCFFAA
#define CLR_BLUE								0x0000BBAA
#define CLR_PINK 								0xFF66FFAA

#define CLR_AQUA 0x00FFFFFF
#define CLR_AQUAGREEN 0x7FFFD4FF

#define CLR_BLUEVILOT 0x8A2BE2FF
#define CLR_DARKGREEN 0x006400FF
#define CLR_GOLDENROD 0xDAA520FF
