#define S "{0080FF}"
#define W "{C0C0C0}"
#define R "{FF0000}"
//Shades of red
#define COLOR_INDIANRED 0xCD5C5CFF
#define COLOR_LIGHTCORAL 0xF08080FF
#define COLOR_SALMON 0xFA8072FF
#define COLOR_DARKSALMON 0xE9967AFF
#define COLOR_LIGHTSALMON 0xFFA07AFF
#define COLOR_CRIMSON 0xDC143CFF
#define COLOR_RED 0xFF0000FF
#define COLOR_FIREBRICK B22222FF
#define COLOR_DARKRED 0x8B0000FF

//Shades of pink
#define COLOR_PINK 0xFFC0CBFF
#define COLOR_LIGHTPINK 0xFFB6C1FF
#define COLOR_HOTPINK 0xFF69B4FF
#define COLOR_DEEPPINK 0xFF1493FF
#define COLOR_MEDIUMVIOLETRED 0xC71585FF
#define COLOR_PALEVIOLETRED 0xDB7093FF

//Shades of Orange
#define COLOR_CORAL 0xFF7F50FF
#define COLOR_TOMATO 0xFF6347FF
#define COLOR_ORANGERED 0xFF4500FF
#define COLOR_DARKORANGE 0xFF8C00FF
#define COLOR_ORANGE 0xFFA500FF

//Shades of Yellow
#define COLOR_GOLD 0xFFD700FF
#define COLOR_YELLOW 0xFFFF00FF
#define COLOR_LIGHTYELLOW 0xFFFFE0FF
#define COLOR_LEMONCHIFFON 0xFFFACDFF
#define COLOR_LIGHTGOLDENRODYELLOW 0xFAFAD2FF
#define COLOR_PAPAYAWHIP 0xFFEFD5FF
#define COLOR_MOCCASIN 0xFFE4B5FF
#define COLOR_PEACHPUFF 0xFFDAB9FF
#define COLOR_PALEGOLDENROD 0xEEE8AAFF
#define COLOR_KHAKI 0xF0E68CFF
#define COLOR_DARKKHAKI 0xBDB76BFF

//Shades of Purple
#define COLOR_LAVENDER 0xE6E6FAFF
#define COLOR_THISTLE 0xD8BFD8FF
#define COLOR_PLUM 0xDDA0DDFF
#define COLOR_VIOLET 0xEE82EEFF
#define COLOR_ORCHID 0xDA70D6FF
#define COLOR_FUCHSIA 0xFF00FFFF
#define COLOR_MAGENTA 0xFF00FFFF
#define COLOR_MEDIUMORCHID 0xBA55D3FF
#define COLOR_MEDIUMPURPLE 0x9370DBFF
#define COLOR_AMETHYST 0x9966CCFF
#define COLOR_BLUEVIOLET 0x8A2BE2FF
#define COLOR_DARKVIOLET 0x9400D3FF
#define COLOR_DARKORCHID 0x9932CCFF
#define COLOR_DARKMAGENTA 0x8B008BFF
#define COLOR_PURPLE 0x800080FF
#define COLOR_INDIGO 0x4B0082FF
#define COLOR_SLATEBLUE 0x6A5ACDFF
#define COLOR_DARKSLATEBLUE 0x483D8BFF
#define COLOR_MEDIUMSLATEBLUE 0x7B68EEFF

//Shades of Green
#define COLOR_GREENYELLOW 0xADFF2FFF
#define COLOR_CHARTREUSE 0x7FFF00FF
#define COLOR_LAWNGREEN 0x7CFC00FF
#define COLOR_LIME 0x00FF00FF
#define COLOR_LIMEGREEN 0x32CD32FF
#define COLOR_PALEGREEN 0x98FB98FF
#define COLOR_LIGHTGREEN 0x90EE90FF
#define COLOR_MEDIUMSPRINGGREEN 0x00FA9AFF
#define COLOR_SPRINGGREEN 0x00FF7FFF
#define COLOR_MEDIUMSEAGREEN 0x3CB371FF
#define COLOR_SEAGREEN 0x2E8B57FF
#define COLOR_FORESTGREEN 0x228B22FF
#define COLOR_GREEN 0x008000FF
#define COLOR_DARKGREEN 0x006400FF
#define COLOR_YELLOWGREEN 0x9ACD32FF
#define COLOR_OLIVEDRAB 0x6B8E23FF
#define COLOR_OLIVE 0x808000FF
#define COLOR_DARKOLIVEGREEN 0x556B2FFF
#define COLOR_MEDIUMAQUAMARINE 0x66CDAAFF
#define COLOR_DARKSEAGREEN 0x8FBC8FFF
#define COLOR_LIGHTSEAGREEN 0x20B2AAFF
#define COLOR_DARKCYAN 0x008B8BFF
#define COLOR_TEAL 0x008080FF

//Shades of Blue/Cyan
#define COLOR_AQUA 0x00FFFFFF
#define COLOR_CYAN 0x00FFFFFF
#define COLOR_LIGHTCYAN 0xE0FFFFFF
#define COLOR_PALETURQUOISE 0xAFEEEEFF
#define COLOR_AQUAMARINE 0x7FFFD4FF
#define COLOR_TURQUOISE 0x40E0D0FF
#define COLOR_MEDIUMTURQUOISE 0x48D1CC
#define COLOR_DARKTURQUOISE 0x00CED1FF
#define COLOR_CADETBLUE 0x5F9EA0FF
#define COLOR_STEELBLUE 0x4682B4FF
#define COLOR_LIGHTSTEELBLUE 0xB0C4DEFF
#define COLOR_POWDERBLUE 0xB0E0E6FF
#define COLOR_LIGHTBLUE 0xADD8E6FF
#define COLOR_SKYBLUE 0x87CEEBFF
#define COLOR_LIGHTSKYBLUE 0x87CEFAFF
#define COLOR_DEEPSKYBLUE 0x00BFFFFF
#define COLOR_DODGERBLUE 0x1E90FFFF
#define COLOR_CORNFLOWERBLUE 0x6495EDFF
#define COLOR_MEDIUMSLATEBLUE 0x7B68EEFF
#define COLOR_ROYALBLUE 0x4169E1FF
#define COLOR_BLUE 0x0000FFFF
#define COLOR_MEDIUMBLUE 0x0000CDFF
#define DARKBLUE 0x00008BFF
#define COLOR_NAVY 0x000080FF
#define COLOR_MIDNIGHTBLUE 0x191970FF

//Shades of Brown
#define COLOR_CORNSILK 0xFFF8DCFF
#define COLOR_BLANCHEDALMOND 0xFFEBCDFF
#define COLOR_BISQUE 0xFFE4C4FF
#define COLOR_NAVAJOWHITE 0xFFDEADFF
#define COLOR_WHEAT 0xF5DEB3FF
#define COLOR_BURLYWOOD 0xDEB887FF
#define COLOR_TAN 0xD2B48CFF
#define COLOR_ROSYBROWN 0xBC8F8FFF
#define COLOR_SANDYBROWN 0xF4A460FF
#define COLOR_DARKGOLDENROD 0xB8860BFF
#define COLOR_PERU 0xCD853FFF
#define COLOR_SADDLEBROWN 0x8B4513FF
#define COLOR_SIENNA 0xA0522DFF
#define COLOR_BROWN 0xA52A2AFF
#define COLOR_MAROON 0x800000FF

//Shades of Grey
#define COLOR_WHITE 0xFFFFFFFF
#define COLOR_GAINSBORO 0xDCDCDCFF
#define COLOR_LIGHTGREY 0xD3D3D3FF
#define COLOR_SILVER 0xC0C0C0FF
#define COLOR_DARKGRAY 0xA9A9A9FF
#define COLOR_GRAY 0x808080FF
#define COLOR_DIMGRAY 0x696969FF
#define COLOR_LIGHTSLATEGRAY 0x778899FF
#define COLOR_SLATEGRAY 0x708090FF
#define COLOR_DARKSLATEGRAY 0x2F4F4FFF
#define COLOR_BLACK 0x000000FF



#define TOTAL_ITEMS         207
#define SELECTION_ITEMS 	21
#define ITEMS_PER_LINE  	7

#define HEADER_TEXT "Vehicles"
#define NEXT_TEXT   "Next"
#define PREV_TEXT   "Prev"

#define DIALOG_BASE_X   	75.0
#define DIALOG_BASE_Y   	130.0
#define DIALOG_WIDTH    	550.0
#define DIALOG_HEIGHT   	180.0
#define SPRITE_DIM_X    	60.0
#define SPRITE_DIM_Y    	70.0
//0HIDE

	
#define Loop:<%0,%1>    \
		for( new %0; %0 < %1; %0++)

/*
	With this definition you cannot be bugged while hiding.
	Keeping it uncommented will remove the object each time
	you are not crouching using OnPlayerUpdate
	
	Comment this if you are experiencing any lag from the script.
*/
	#define PERFECTION
/*

*/
new
	bool:Activated[MAX_PLAYERS char],
	Hidden[MAX_PLAYERS char],
	CurrentObject[MAX_PLAYERS char]
;
enum
	e_objects
	{
		o_id,		o_n[15],	o_b,
		Float:o_x,	Float:o_y,	Float:o_z,
		Float:o_rx,	Float:o_ry,	Float:o_rz,
		Float:o_sx,	Float:o_sy,	Float:o_sz
	}

enum
	e_dialogs
	{
	    Empty = 5555,
	    List = 5556
	}

new
	ObjectInfo[33][e_objects] =
	{
	    {1221, "Box 1", 11, 0.331851, -0.387647, 0.108080, 62.871932, 3.603914, 279.105468, 1.500000, 1.500000, 1.500000},
	    {1220, "Box 2",11, 0.331851, -0.387647, 0.108080, 62.871932, 3.603914, 279.105468, 1.500000, 1.500000, 1.500000},
	    {2912, "Box 3", 10, -0.117735, -0.402220, -0.766344, 356.370971, 357.288360, 5.631556, 1.500000, 1.600000, 1.500000},
	    {964, "Army Box", 11, 0.180357, 0.045067, -0.323517, 63.705467, 4.868588, 165.003601, 1.000000, 1.000000, 1.299999},
	    {1271, "Gun Box", 11, 0.316308, -0.396371, 0.129949, 65.029396, 4.721271, 279.105468, 1.500000, 1.500000, 1.500000},
	    {1367, "Post Box 1", 11, 0.230588, -0.647528, 0.151942, 65.029396, 4.721271, 279.105468, 1.500000, 1.500000, 1.500000},
	    {1291, "Post Box 2", 11, 0.285487, -0.645864, 0.129949, 65.029396, 4.721271, 279.105468, 1.500000, 1.500000, 1.500000},
	    {800, "Bush 1", 11, 0.366527, -0.542696, -0.005478, 35.919593, 8.222164, 141.222518, 0.432692, 0.400000, 0.400000},
	    {823, "Bush 2", 11, 0.366527, -0.542696, -0.005478, 60.612785, 10.375102, 165.003601, 0.312109, 0.300000, 0.300000},
	    {824, "Bush 3", 11, 0.366527, -0.542696, -0.005478, 60.612785, 10.375102, 165.003601, 0.312109, 0.300000, 0.300000},
	    {825, "Bush 4", 11, 0.366527, -0.542696, -0.005478, 60.612785, 10.375102, 165.003601, 0.312109, 0.300000, 0.300000},
	    {754, "Cactus Bush", 11, 0.312796, 0.180289, -0.285668, 63.705467, 4.868588, 165.003601, 1.200027, 1.252762, 2.480148},
	    {653, "Cactus Plant", 11, -0.121614, 0.075794, -0.285668, 63.705467, 4.868588, 165.003601, 0.800000, 0.800000, 0.800000},
	    {831, "Dead Tree", 11, 0.366527, -0.542696, -0.005478, 60.612785, 10.375102, 165.003601, 0.600000, 0.600000, 0.600000},
	    {1370, "Flame Drum", 11, 0.230588, -0.647528, 0.151942, 63.663352, 5.211647, 103.045799, 1.500000, 1.500000, 1.500000},
	    {1371, "Hippo Bin", 11, 0.230588, -0.647528, 0.151942, 65.029396, 4.721271, 279.105468, 1.500000, 1.500000, 1.500000},
	    {1225, "Barrel 1", 11, 0.331851, -0.387647, 0.108080, 62.871932, 3.603914, 279.105468, 1.500000, 1.500000, 1.500000},
	    {1222, "Barrel 2", 11, 0.331851, -0.387647, 0.108080, 62.871932, 3.603914, 279.105468, 1.500000, 1.500000, 1.500000},
	    {1218, "Barrel 3", 11, 0.331851, -0.387647, 0.108080, 62.871932, 3.603914, 279.105468, 1.500000, 1.500000, 1.5000},
	    {1217, "Barrel 4", 11, 0.331851, -0.387647, 0.108080, 62.871932, 3.603914, 279.105468, 1.500000, 1.500000, 1.500000},
	    {1362, "Fire Bin", 11, 0.230588, -0.647528, 0.151942, 65.029396, 4.721271, 279.105468, 1.500000, 1.500000, 1.500000},
	    {1347, "Waste Bin", 11, 0.230588, -0.647528, 0.151942, 65.029396, 4.721271, 279.105468, 1.500000, 1.500000, 1.500000},
	    {1339, "Bin 1", 11, 0.230588, -0.647528, 0.151942, 65.029396, 4.721271, 279.105468, 1.500000, 1.500000, 1.500000},
	    {1337, "Bin 2", 11, 0.230588, -0.647528, 0.151942, 65.029396, 4.721271, 279.105468, 1.500000, 1.500000, 1.500000},
	    {1330, "Trash Can 1", 11, 0.285487, -0.587944, 0.121327, 65.029396, 4.721271, 279.105468, 1.500000, 1.500000, 1.500000},
	    {1329, "Trash Can 2", 11, 0.285487, -0.645864, 0.129949, 65.029396, 4.721271, 279.105468, 1.500000, 1.500000, 1.500000},
	    {1328, "Trash Can 3", 11, 0.285487, -0.645864, 0.129949, 65.029396, 4.721271, 279.105468, 1.500000, 1.500000, 1.500000},
	    {1264, "Trash Bag", 11, 0.331851, -0.534445, -0.022953, 65.029396, 4.721271, 279.105468, 1.500000, 1.500000, 1.500000},
	    {1237, "Barrier", 11, 0.331851, 0.015704, -0.173188, 65.029396, 4.721271, 279.105468, 1.500000, 1.500000, 1.500000},
	    {1208, "Wash Machine", 11, 0.292449, 0.018611, -0.236802, 64.272399, 6.367418, 97.481346, 1.500000, 1.500000, 1.500000},
	    {1304, "Rock 1", 11, 0.285487, -0.645864, 0.129949, 65.029396, 4.721271, 279.105468, 1.500000, 1.500000, 1.500000},
	    {1303, "Rock 2", 11, 0.285487, -0.645864, 0.129949, 65.029396, 4.721271, 279.105468, 1.500000, 1.500000, 1.500000},
	    {1305, "Rock 3", 11, 0.285487, -0.645864, 0.129949, 65.029396, 4.721271, 279.105468, 0.800000, 0.800000, 0.800000}
	};
	
	
	
new gTotalItems = TOTAL_ITEMS;
new PlayerText:gCurrentPageTextDrawId[MAX_PLAYERS];
new PlayerText:gHeaderTextDrawId[MAX_PLAYERS];
new PlayerText:gBackgroundTextDrawId[MAX_PLAYERS];
new PlayerText:gNextButtonTextDrawId[MAX_PLAYERS];
new PlayerText:gPrevButtonTextDrawId[MAX_PLAYERS];
new PlayerText:gSelectionItems[MAX_PLAYERS][SELECTION_ITEMS];
new gSelectionItemsTag[MAX_PLAYERS][SELECTION_ITEMS];
new gItemAt[MAX_PLAYERS];

new gItemList[TOTAL_ITEMS] = {
400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,
431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,450,451,452,453,454,455,456,457,458,459,460,461,
462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,
493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,
524,525,526,527,528,529,530,531,532,533,534,535,536,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,
555,556,557,558,559,560,561,562,563,564,565,566,567,568,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,
586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611
};





new aVehicleNames[212][] =
{
	{"Landstalker"},
	{"Bravura"},
	{"Buffalo"},
	{"Linerunner"},
	{"Perrenial"},
	{"Sentinel"},
	{"Dumper"},
	{"Firetruck"},
	{"Trashmaster"},
	{"Stretch"},
	{"Manana"},
	{"Infernus"},
	{"Voodoo"},
	{"Pony"},
	{"Mule"},
	{"Cheetah"},
	{"Ambulance"},
	{"Leviathan"},
	{"Moonbeam"},
	{"Esperanto"},
	{"Taxi"},
	{"Washington"},
	{"Bobcat"},
	{"Mr Whoopee"},
	{"BF Injection"},
	{"Hunter"},
	{"Premier"},
	{"Enforcer"},
	{"Securicar"},
	{"Banshee"},
	{"Predator"},
	{"Bus"},
	{"Rhino"},
	{"Barracks"},
	{"Hotknife"},
	{"Trailer 1"},
	{"Previon"},
	{"Coach"},
	{"Cabbie"},
	{"Stallion"},
	{"Rumpo"},
	{"RC Bandit"},
	{"Romero"},
	{"Packer"},
	{"Monster"},
	{"Admiral"},
	{"Squalo"},
	{"Seasparrow"},
	{"Pizzaboy"},
	{"Tram"},
	{"Trailer 2"},
	{"Turismo"},
	{"Speeder"},
	{"Reefer"},
	{"Tropic"},
	{"Flatbed"},
	{"Yankee"},
	{"Caddy"},
	{"Solair"},
	{"Berkley's RC Van"},
	{"Skimmer"},
	{"PCJ-600"},
	{"Faggio"},
	{"Freeway"},
	{"RC Baron"},
	{"RC Raider"},
	{"Glendale"},
	{"Oceanic"},
	{"Sanchez"},
	{"Sparrow"},
	{"Patriot"},
	{"Quad"},
	{"Coastguard"},
	{"Dinghy"},
	{"Hermes"},
	{"Sabre"},
	{"Rustler"},
	{"ZR-350"},
	{"Walton"},
	{"Regina"},
	{"Comet"},
	{"BMX"},
	{"Burrito"},
	{"Camper"},
	{"Marquis"},
	{"Baggage"},
	{"Dozer"},
	{"Maverick"},
	{"News Chopper"},
	{"Rancher"},
	{"FBI Rancher"},
	{"Virgo"},
	{"Greenwood"},
	{"Jetmax"},
	{"Hotring"},
	{"Sandking"},
	{"Blista Compact"},
	{"Police Maverick"},
	{"Boxville"},
	{"Benson"},
	{"Mesa"},
	{"RC Goblin"},
	{"Hotring Racer A"},
	{"Hotring Racer B"},
	{"Bloodring Banger"},
	{"Rancher"},
	{"Super GT"},
	{"Elegant"},
	{"Journey"},
	{"Bike"},
	{"Mountain Bike"},
	{"Beagle"},
	{"Cropdust"},
	{"Stunt"},
	{"Tanker"},
	{"Roadtrain"},
	{"Nebula"},
	{"Majestic"},
	{"Buccaneer"},
	{"Shamal"},
	{"Hydra"},
	{"FCR-900"},
	{"NRG-500"},
	{"HPV1000"},
	{"Cement Truck"},
	{"Tow Truck"},
	{"Fortune"},
	{"Cadrona"},
	{"FBI Truck"},
	{"Willard"},
	{"Forklift"},
	{"Tractor"},
	{"Combine"},
	{"Feltzer"},
	{"Remington"},
	{"Slamvan"},
	{"Blade"},
	{"Freight"},
	{"Streak"},
	{"Vortex"},
	{"Vincent"},
	{"Bullet"},
	{"Clover"},
	{"Sadler"},
	{"Firetruck LA"},
	{"Hustler"},
	{"Intruder"},
	{"Primo"},
	{"Cargobob"},
	{"Tampa"},
	{"Sunrise"},
	{"Merit"},
	{"Utility"},
	{"Nevada"},
	{"Yosemite"},
	{"Windsor"},
	{"Monster A"},
	{"Monster B"},
	{"Uranus"},
	{"Jester"},
	{"Sultan"},
	{"Stratum"},
	{"Elegy"},
	{"Raindance"},
	{"RC Tiger"},
	{"Flash"},
	{"Tahoma"},
	{"Savanna"},
	{"Bandito"},
	{"Freight Flat"},
	{"Streak Carriage"},
	{"Kart"},
	{"Mower"},
	{"Duneride"},
	{"Sweeper"},
	{"Broadway"},
	{"Tornado"},
	{"AT-400"},
	{"DFT-30"},
	{"Huntley"},
	{"Stafford"},
	{"BF-400"},
	{"Newsvan"},
	{"Tug"},
	{"Trailer 3"},
	{"Emperor"},
	{"Wayfarer"},
	{"Euros"},
	{"Hotdog"},
	{"Club"},
	{"Freight Carriage"},
	{"Trailer 3"},
	{"Andromada"},
	{"Dodo"},
	{"RC Cam"},
	{"Launch"},
	{"Police Car (LSPD)"},
	{"Police Car (SFPD)"},
	{"Police Car (LVPD)"},
	{"Police Ranger"},
	{"Picador"},
	{"S.W.A.T. Van"},
	{"Alpha"},
	{"Phoenix"},
	{"Glendale"},
	{"Sadler"},
	{"Luggage Trailer A"},
	{"Luggage Trailer B"},
	{"Stair Trailer"},
	{"Boxville"},
	{"Farm Plow"},
	{"Utility Trailer"}
};

new	playerColors[500] = {
	-8355585, -32513, -2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319, -8355585,
	-32513, -2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319, -8355585, -32513,
	-2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319, -8355585, -32513, -2130738945,
	16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319, -8355585, -32513, -2130738945, 16744703, -2130706433,
	-16744193, -8339201, -8323073, -2130771713, 16728319, -8355585, -32513, -2130738945, 16744703, -2130706433, -16744193, -8339201,
	-8323073, -2130771713, 16728319, -8355585, -32513, -2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713,
	16728319, -8355585, -32513, -2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319, -8355585,
	-32513, -2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319, -8355585, -32513, -2130738945,
	16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319, -8355585, -32513, -2130738945, 16744703, -2130706433,
	-16744193, -8339201, -8323073, -2130771713, 16728319, -8355585, -32513, -2130738945, 16744703, -2130706433, -16744193, -8339201,
	-8323073, -2130771713, 16728319, -8355585, -32513, -2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713,
	16728319, -8355585, -32513, -2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319, -8355585,
	-32513, -2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319, -8355585, -32513, -2130738945,
	16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319, -8355585, -32513, -2130738945, 16744703, -2130706433,
	-16744193, -8339201, -8323073, -2130771713, 16728319, -8355585, -32513, -2130738945, 16744703, -2130706433, -16744193, -8339201,
	-8323073, -2130771713, 16728319, -8355585, -32513, -2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713,
	16728319, -8355585, -32513, -2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319, -8355585,
	-32513, -2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319, -8355585, -32513, -2130738945,
	16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319, -8355585, -32513, -2130738945, 16744703, -2130706433,
	-16744193, -8339201, -8323073, -2130771713, 16728319, -8355585, -32513, -2130738945, 16744703, -2130706433, -16744193, -8339201,
	-8323073, -2130771713, 16728319, -8355585, -32513, -2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713,
	16728319, -8355585, -32513, -2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319, -8355585,
	-32513, -2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319, -8355585, -32513, -2130738945,
	16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319, -8355585, -32513, -2130738945, 16744703, -2130706433,
	-16744193, -8339201, -8323073, -2130771713, 16728319, -8355585, -32513, -2130738945, 16744703, -2130706433, -16744193, -8339201,
	-8323073, -2130771713, 16728319, -8355585, -32513, -2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713,
	16728319, -8355585, -32513, -2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319, -8355585,
	-32513, -2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319, -8355585, -32513, -2130738945,
	16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319, -8355585, -32513, -2130738945, 16744703, -2130706433,
	-16744193, -8339201, -8323073, -2130771713, 16728319, -8355585, -32513, -2130738945, 16744703, -2130706433, -16744193, -8339201,
	-8323073, -2130771713, 16728319, -8355585, -32513, -2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713,
	16728319, -8355585, -32513, -2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319, -8355585,
	-32513, -2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319, -8355585, -32513, -2130738945,
	16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319, -8355585, -32513, -2130738945, 16744703, -2130706433,
	-16744193, -8339201, -8323073, -2130771713, 16728319, -8355585, -32513, -2130738945, 16744703, -2130706433, -16744193, -8339201,
	-8323073, -2130771713, 16728319, -8355585, -32513, -2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713,
	16728319, -8355585, -32513, -2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319, -8355585,
	-32513, -2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319, -8355585, -32513, -2130738945,
	16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319, -8355585, -32513, -2130738945, 16744703, -2130706433,
	-16744193, -8339201, -8323073, -2130771713, 16728319, -8355585, -32513, -2130738945, 16744703, -2130706433, -16744193, -8339201,
	-8323073, -2130771713, 16728319, -8355585, -32513, -2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713,
	16728319, -8355585, -32513, -2130738945, 16744703, -2130706433, -16744193, -8339201, -8323073, -2130771713, 16728319
};

new aWeaponNames[][32] = {
	{"Unarmed (Fist)"}, // 0
	{"Brass Knuckles"}, // 1
	{"Golf Club"}, // 2
	{"Night Stick"}, // 3
	{"Knife"}, // 4
	{"Baseball Bat"}, // 5
	{"Shovel"}, // 6
	{"Pool Cue"}, // 7
	{"Katana"}, // 8
	{"Chainsaw"}, // 9
	{"Purple Dildo"}, // 10
	{"Big White Vibrator"}, // 11
	{"Medium White Vibrator"}, // 12
	{"Small White Vibrator"}, // 13
	{"Flowers"}, // 14
	{"Cane"}, // 15
	{"Grenade"}, // 16
	{"Teargas"}, // 17
	{"Molotov"}, // 18
	{" "}, // 19
	{" "}, // 20
	{" "}, // 21
	{"Colt 45"}, // 22
	{"Colt 45 (Silenced)"}, // 23
	{"Desert Eagle"}, // 24
	{"Normal Shotgun"}, // 25
	{"Sawnoff Shotgun"}, // 26
	{"Combat Shotgun"}, // 27
	{"Micro Uzi (Mac 10)"}, // 28
	{"MP5"}, // 29
	{"AK47"}, // 30
	{"M4"}, // 31
	{"Tec9"}, // 32
	{"Country Rifle"}, // 33
	{"Sniper Rifle"}, // 34
	{"Rocket Launcher"}, // 35
	{"Heat-Seeking Rocket Launcher"}, // 36
	{"Flamethrower"}, // 37
	{"Minigun"}, // 38
	{"Satchel Charge"}, // 39
	{"Detonator"}, // 40
	{"Spray Can"}, // 41
	{"Fire Extinguisher"}, // 42
	{"Camera"}, // 43
	{"Night Vision Goggles"}, // 44
	{"Infrared Vision Goggles"}, // 45
	{"Parachute"}, // 46
	{"Fake Pistol"} // 47
};

IsNumeric(const string[])
{
    for (new i = 0, j = strlen(string); i < j; i++)
    {
        if (string[i] > '9' || string[i] < '0') return 0;
    }
    return 1;
}


Init_PCAR(playerid){
	// Init all of the textdraw related globals
	gHeaderTextDrawId[playerid] = PlayerText:INVALID_TEXT_DRAW;
    gBackgroundTextDrawId[playerid] = PlayerText:INVALID_TEXT_DRAW;
    gCurrentPageTextDrawId[playerid] = PlayerText:INVALID_TEXT_DRAW;
    gNextButtonTextDrawId[playerid] = PlayerText:INVALID_TEXT_DRAW;
    gPrevButtonTextDrawId[playerid] = PlayerText:INVALID_TEXT_DRAW;
    
    for(new x=0; x < SELECTION_ITEMS; x++) {
        gSelectionItems[playerid][x] = PlayerText:INVALID_TEXT_DRAW;
	}
	
	gItemAt[playerid] = 0;

}

GetNumberOfPages()
{
	if((gTotalItems >= SELECTION_ITEMS) && (gTotalItems % SELECTION_ITEMS) == 0)
	{
		return (gTotalItems / SELECTION_ITEMS);
	}
	else return (gTotalItems / SELECTION_ITEMS) + 1;
}

//------------------------------------------------

PlayerText:CreateCurrentPageTextDraw(playerid, Float:Xpos, Float:Ypos)
{
	new PlayerText:txtInit;
   	txtInit = CreatePlayerTextDraw(playerid, Xpos, Ypos, "0/0");
   	PlayerTextDrawUseBox(playerid, txtInit, 0);
	PlayerTextDrawLetterSize(playerid, txtInit, 0.4, 1.1);
	PlayerTextDrawFont(playerid, txtInit, 1);
	PlayerTextDrawSetShadow(playerid, txtInit, 0);
    PlayerTextDrawSetOutline(playerid, txtInit, 1);
    PlayerTextDrawColor(playerid, txtInit, 0xACCBF1FF);
    PlayerTextDrawShow(playerid, txtInit);
    return txtInit;
}

//------------------------------------------------
// Creates a button textdraw and returns the textdraw ID.

PlayerText:CreatePlayerDialogButton(playerid, Float:Xpos, Float:Ypos, Float:Width, Float:Height, button_text[])
{
 	new PlayerText:txtInit;
   	txtInit = CreatePlayerTextDraw(playerid, Xpos, Ypos, button_text);
   	PlayerTextDrawUseBox(playerid, txtInit, 1);
   	PlayerTextDrawBoxColor(playerid, txtInit, 0x000000FF);
   	PlayerTextDrawBackgroundColor(playerid, txtInit, 0x000000FF);
	PlayerTextDrawLetterSize(playerid, txtInit, 0.4, 1.1);
	PlayerTextDrawFont(playerid, txtInit, 1);
	PlayerTextDrawSetShadow(playerid, txtInit, 0); // no shadow
    PlayerTextDrawSetOutline(playerid, txtInit, 0);
    PlayerTextDrawColor(playerid, txtInit, 0x4A5A6BFF);
    PlayerTextDrawSetSelectable(playerid, txtInit, 1);
    PlayerTextDrawAlignment(playerid, txtInit, 2);
    PlayerTextDrawTextSize(playerid, txtInit, Height, Width); // The width and height are reversed for centering.. something the game does <g>
    PlayerTextDrawShow(playerid, txtInit);
    return txtInit;
}
 
//------------------------------------------------

PlayerText:CreatePlayerHeaderTextDraw(playerid, Float:Xpos, Float:Ypos, header_text[])
{
	new PlayerText:txtInit;
   	txtInit = CreatePlayerTextDraw(playerid, Xpos, Ypos, header_text);
   	PlayerTextDrawUseBox(playerid, txtInit, 0);
	PlayerTextDrawLetterSize(playerid, txtInit, 1.25, 3.0);
	PlayerTextDrawFont(playerid, txtInit, 0);
	PlayerTextDrawSetShadow(playerid, txtInit, 0);
    PlayerTextDrawSetOutline(playerid, txtInit, 1);
    PlayerTextDrawColor(playerid, txtInit, 0xACCBF1FF);
    PlayerTextDrawShow(playerid, txtInit);
    return txtInit;
}

//------------------------------------------------

PlayerText:CreatePlayerBackgroundTextDraw(playerid, Float:Xpos, Float:Ypos, Float:Width, Float:Height)
{
	new PlayerText:txtBackground = CreatePlayerTextDraw(playerid, Xpos, Ypos,
	"                                            ~n~"); // enough space for everyone
    PlayerTextDrawUseBox(playerid, txtBackground, 1);
    PlayerTextDrawBoxColor(playerid, txtBackground, 0x00000099);
	PlayerTextDrawLetterSize(playerid, txtBackground, 5.0, 5.0);
	PlayerTextDrawFont(playerid, txtBackground, 0);
	PlayerTextDrawSetShadow(playerid, txtBackground, 0);
    PlayerTextDrawSetOutline(playerid, txtBackground, 0);
    PlayerTextDrawColor(playerid, txtBackground,0x000000FF);
    PlayerTextDrawTextSize(playerid, txtBackground, Width, Height);
   	PlayerTextDrawBackgroundColor(playerid, txtBackground, 0x00000099);
    PlayerTextDrawShow(playerid, txtBackground);
    return txtBackground;
}

//------------------------------------------------
// Creates a model preview sprite

PlayerText:CreateModelPreviewTextDraw(playerid, modelindex, Float:Xpos, Float:Ypos, Float:width, Float:height)
{
    new PlayerText:txtPlayerSprite = CreatePlayerTextDraw(playerid, Xpos, Ypos, ""); // it has to be set with SetText later
    PlayerTextDrawFont(playerid, txtPlayerSprite, TEXT_DRAW_FONT_MODEL_PREVIEW);
    PlayerTextDrawColor(playerid, txtPlayerSprite, 0xFFFFFFFF);
    PlayerTextDrawBackgroundColor(playerid, txtPlayerSprite, 0x000000EE);
    PlayerTextDrawTextSize(playerid, txtPlayerSprite, width, height); // Text size is the Width:Height
    PlayerTextDrawSetPreviewModel(playerid, txtPlayerSprite, modelindex);
    PlayerTextDrawSetPreviewRot(playerid,txtPlayerSprite, -16.0, 0.0, -55.0);
    PlayerTextDrawSetSelectable(playerid, txtPlayerSprite, 1);
    PlayerTextDrawShow(playerid,txtPlayerSprite);
    return txtPlayerSprite;
}

//------------------------------------------------

DestroyPlayerModelPreviews(playerid)
{
	new x=0;
	while(x != SELECTION_ITEMS) {
	    if(gSelectionItems[playerid][x] != PlayerText:INVALID_TEXT_DRAW) {
			PlayerTextDrawDestroy(playerid, gSelectionItems[playerid][x]);
			gSelectionItems[playerid][x] = PlayerText:INVALID_TEXT_DRAW;
		}
		x++;
	}
}

//------------------------------------------------

ShowPlayerModelPreviews(playerid)
{
    new x=0;
	new Float:BaseX = DIALOG_BASE_X;
	new Float:BaseY = DIALOG_BASE_Y - (SPRITE_DIM_Y * 0.33); // down a bit
	new linetracker = 0;
	
	new itemat = GetPVarInt(playerid, "vspawner_page") * SELECTION_ITEMS;
	
	// Destroy any previous ones created
	DestroyPlayerModelPreviews(playerid);

	while(x != SELECTION_ITEMS && itemat < gTotalItems) {
	    if(linetracker == 0) {
	        BaseX = DIALOG_BASE_X + 25.0; // in a bit from the box
	        BaseY += SPRITE_DIM_Y + 1.0; // move on the Y for the next line
		}
  		gSelectionItems[playerid][x] = CreateModelPreviewTextDraw(playerid, gItemList[itemat], BaseX, BaseY, SPRITE_DIM_X, SPRITE_DIM_Y);
  		gSelectionItemsTag[playerid][x] = gItemList[itemat];
		BaseX += SPRITE_DIM_X + 1.0; // move on the X for the next sprite
		linetracker++;
		if(linetracker == ITEMS_PER_LINE) linetracker = 0;
		itemat++;
		x++;
	}
}

//------------------------------------------------

UpdatePageTextDraw(playerid)
{
	new PageText[64+1];
	format(PageText, 64, "%d/%d", GetPVarInt(playerid,"vspawner_page") + 1, GetNumberOfPages());
	PlayerTextDrawSetString(playerid, gCurrentPageTextDrawId[playerid], PageText);
}

//------------------------------------------------

CreateSelectionMenu(playerid)
{
    gBackgroundTextDrawId[playerid] = CreatePlayerBackgroundTextDraw(playerid, DIALOG_BASE_X, DIALOG_BASE_Y + 20.0, DIALOG_WIDTH, DIALOG_HEIGHT);
    gHeaderTextDrawId[playerid] = CreatePlayerHeaderTextDraw(playerid, DIALOG_BASE_X, DIALOG_BASE_Y, HEADER_TEXT);
    gCurrentPageTextDrawId[playerid] = CreateCurrentPageTextDraw(playerid, DIALOG_WIDTH - 30.0, DIALOG_BASE_Y + 15.0);
    gNextButtonTextDrawId[playerid] = CreatePlayerDialogButton(playerid, DIALOG_WIDTH - 30.0, DIALOG_BASE_Y+DIALOG_HEIGHT+100.0, 50.0, 16.0, NEXT_TEXT);
    gPrevButtonTextDrawId[playerid] = CreatePlayerDialogButton(playerid, DIALOG_WIDTH - 90.0, DIALOG_BASE_Y+DIALOG_HEIGHT+100.0, 50.0, 16.0, PREV_TEXT);

    ShowPlayerModelPreviews(playerid);
    UpdatePageTextDraw(playerid);
}

//------------------------------------------------

DestroySelectionMenu(playerid)
{
	DestroyPlayerModelPreviews(playerid);

	PlayerTextDrawDestroy(playerid, gHeaderTextDrawId[playerid]);
	PlayerTextDrawDestroy(playerid, gBackgroundTextDrawId[playerid]);
	PlayerTextDrawDestroy(playerid, gCurrentPageTextDrawId[playerid]);
	PlayerTextDrawDestroy(playerid, gNextButtonTextDrawId[playerid]);
	PlayerTextDrawDestroy(playerid, gPrevButtonTextDrawId[playerid]);

	gHeaderTextDrawId[playerid] = PlayerText:INVALID_TEXT_DRAW;
    gBackgroundTextDrawId[playerid] = PlayerText:INVALID_TEXT_DRAW;
    gCurrentPageTextDrawId[playerid] = PlayerText:INVALID_TEXT_DRAW;
    gNextButtonTextDrawId[playerid] = PlayerText:INVALID_TEXT_DRAW;
    gPrevButtonTextDrawId[playerid] = PlayerText:INVALID_TEXT_DRAW;
}

//------------------------------------------------
Load3DTextLabels(){
	Create3DTextLabel("Welcome to JustNowMovies!",0xFFFFFFFF,1699.5048,1431.4244,16.00,40,0);
	Create3DTextLabel("Server Dev By:Episodes",0xFFFF00FF,1699.5048,1431.4244,15.5029,40,0);
	Create3DTextLabel("Spport:GTAYY",0xFFFF00FF,1699.5048,1431.4244,15.00,40,0);
	Create3DTextLabel("Website:easy-servers.org",0xFFFF00FF,1699.5048,1431.4244,14.50,40,0);
	Create3DTextLabel("We hope you enjoy playing here",0xFF0000FF,1699.5048,1431.4244,14.00,40,0);
	//-------------------------------------------------------------------------------------
	Create3DTextLabel("Welcome to JustNowMovies!",0x00FF00FF,1477.8623,-1668.2054,23.00,40,0);
	Create3DTextLabel("We hope you enjoy playing here",0xFFFF00FF,1477.8623,-1668.2054,22.50,40,0);
    //Create3DTextLabel("[IP]:mov.gtaun.net:4444",0x00CDFFFF,1477.8623,-1668.2054,22.00,40,0);
	//Create3DTextLabel("需要帮助请输入/help",0xFF0000FF,1477.8623,-1668.2054,21.50,40,0);
    //-------------------------------------------------------------------------------------
	Create3DTextLabel("Welcome to JustNowMovies!",0xFFFF00AA,917.5461,-1221.1047,25.63,20,0,1);
	Create3DTextLabel("Server Dev By:Episodes",0xFFFFFFAA,917.5461,-1221.1047,25.3,20,0,1);
	Create3DTextLabel("Spport:GTAYY",0xFFFFFFAA,917.5461,-1221.1047,24.83,20,0,1);
	//Create3DTextLabel("技术提供：GTA-YY",0xFFFFFFAA,917.5461,-1221.1047,24.63,20,0,1);
	Create3DTextLabel("---------------------",0xAA3333AA,917.5461,-1221.1047,24.43,20,0,1);
	Create3DTextLabel("We hope you enjoy playing here",0xFF6347AA,917.5461,-1221.1047,24.23,20,0,1);
	//-------------------------------------------------------------------------------------
	Create3DTextLabel("Welcome to JustNowMovies!",0x00FF00FF,178.0179,-4200.6860,7.00,40,0);
	Create3DTextLabel("---------------------",0xFFFF00FF,178.0179,-4200.6860,6.50,40,0);
	Create3DTextLabel("We hope you enjoy playing here",0xFF0000FF,178.0179,-4200.6860,6.00,40,0);
    //--------------------------------------------------------------------------------------
	Create3DTextLabel("Welcome to JustNowMovies!",0x00FF00FF,1212.6550,-2041.4308,69.0078,40,0);
	Create3DTextLabel("---------------------",0xFFFF00FF,1212.8279,-2032.8019,68.9984,40,0);
	Create3DTextLabel("We hope you enjoy playing here",0xFF0000FF,1217.2535,-2033.0454,67.3203,40,0);

}



HandlePlayerItemSelection(playerid, selecteditem)
{
 	// In this case we're spawning a vehicle for them
    SpawnVehicle_InfrontOfPlayer(playerid, gSelectionItemsTag[playerid][selecteditem], -1, -1);
}

stock LoadStaticVehiclesFromFile(const filename[])
{
	new File:file_ptr;
	new line[256];
	new var_from_line[64];
	new vehicletype;
	new Float:SpawnX;
	new Float:SpawnY;
	new Float:SpawnZ;
	new Float:SpawnRot;
    new Color1, Color2;
	new index;
	new vehicles_loaded;

	file_ptr = fopen(filename,filemode:io_read);
	if(!file_ptr) return 0;

	vehicles_loaded = 0;

	while(fread(file_ptr,line,256) > 0)
	{
	    index = 0;

	    // Read type
  		index = token_by_delim(line,var_from_line,',',index);
  		if(index == (-1)) continue;
  		vehicletype = strval(var_from_line);
   		if(vehicletype < 400 || vehicletype > 611) continue;

  		// Read X, Y, Z, Rotation
  		index = token_by_delim(line,var_from_line,',',index+1);
  		if(index == (-1)) continue;
  		SpawnX = floatstr(var_from_line);

  		index = token_by_delim(line,var_from_line,',',index+1);
  		if(index == (-1)) continue;
  		SpawnY = floatstr(var_from_line);

  		index = token_by_delim(line,var_from_line,',',index+1);
  		if(index == (-1)) continue;
  		SpawnZ = floatstr(var_from_line);

  		index = token_by_delim(line,var_from_line,',',index+1);
  		if(index == (-1)) continue;
  		SpawnRot = floatstr(var_from_line);

  		// Read Color1, Color2
  		index = token_by_delim(line,var_from_line,',',index+1);
  		if(index == (-1)) continue;
  		Color1 = strval(var_from_line);

  		index = token_by_delim(line,var_from_line,';',index+1);
  		Color2 = strval(var_from_line);

  		//printf("%d,%d,%f,%f,%f,%f,%d,%d",total_vehicles_from_files+vehicles_loaded+1,vehicletype,SpawnX,SpawnY,SpawnZ,SpawnRot,Color1,Color2);

		AddStaticVehicleEx(vehicletype,SpawnX,SpawnY,SpawnZ,SpawnRot,Color1,Color2,(30*60)); // respawn 30 minutes
		vehicles_loaded++;
	}

	fclose(file_ptr);
	printf("Loaded %d vehicles from: %s",vehicles_loaded,filename);
	return vehicles_loaded;
}
stock token_by_delim(const string[], return_str[], delim, start_index)
{
	new x=0;
	while(string[start_index] != EOS && string[start_index] != delim) {
	    return_str[x] = string[start_index];
	    x++;
	    start_index++;
	}
	return_str[x] = EOS;
	if(string[start_index] == EOS) start_index = (-1);
	return start_index;
}

stock ToggleTagName(playerid, toggle)
{
	Loop:<I, MAX_PLAYERS>
	{
	    if(I != INVALID_PLAYER_ID)
	    {
	    	ShowPlayerNameTagForPlayer(I, playerid, toggle);
	    }
	}
}
stock StealthMode(playerid)
{
	Hidden{playerid} = true;
	ToggleTagName(playerid, 0);
	
    SetPlayerColor(playerid, GetPlayerColor(playerid) - (GetPlayerColor(playerid) & 0x000000FF) - 255);
	
	SetPlayerAttachedObject
 	(
		playerid,
		0,
		ObjectInfo[CurrentObject{playerid}][o_id],
		ObjectInfo[CurrentObject{playerid}][o_b],
		ObjectInfo[CurrentObject{playerid}][o_x],
		ObjectInfo[CurrentObject{playerid}][o_y],
		ObjectInfo[CurrentObject{playerid}][o_z],
		ObjectInfo[CurrentObject{playerid}][o_rx],
		ObjectInfo[CurrentObject{playerid}][o_ry],
		ObjectInfo[CurrentObject{playerid}][o_rz],
		ObjectInfo[CurrentObject{playerid}][o_sx],
		ObjectInfo[CurrentObject{playerid}][o_sy],
		ObjectInfo[CurrentObject{playerid}][o_sz]
	);
}
stock RevealPlayer(playerid, toggle = 1)
{
    Hidden{playerid} = false;
	SetPlayerColor(playerid, GetPlayerColor(playerid) - (GetPlayerColor(playerid) & 0x000000FF) + 255);
	RemovePlayerAttachedObject(playerid, 0);
	ToggleTagName(playerid, toggle);
}
stock ShowContent()
{
	new Content[512];

	strcat(Content, "{94ED40}0Hide - Stealthy Filterscript V2{FFFFFF}\n\n", 512);
	strcat(Content, "Created by {94ED40}Zh3r0{FFFFFF} on {94ED40}17 June{FFFFFF}\n", 512);
	strcat(Content, "Type {94ED40}/hide{FFFFFF} to activate/deactivate the stealth mode.!\n", 512);
	strcat(Content, "Type {94ED40}/hideo{FFFFFF} and choose your hiding object!\n\n", 512);
	strcat(Content, "(C)Zh3r0 - Keep the credits");

	return Content;
}