#define PUP_JetPack					370 //飞行器
#define PUP_Info 					1239//"i"字型的icon
#define PUP_HP 						1240//血量icon
#define PUP_Adrenaline 				1241//药丸icon
#define PUP_Armour 					1242//护甲
#define PUP_Bribe 					1247//警星
#define PUP_Camerapu 				1253//录影机
#define PUP_Kill 					1254//骷髅头
#define PUP_BlueProperty 			1272//蓝色小屋
#define PUP_GreenProperty 			1273//绿色小屋
#define PUP_Dollar 					1274// $
#define PUP_Clothing 				1275//衣服
#define PUP_Save 					1277//save磁碟
#define PUP_Kill2Player 			1313//两个骷髅头
#define PUP_2Player 				1314//两个玩家
